/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sghtxjdbhalsqqjwismi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnaHR4amRiaGFsc3Fxandpc21pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNzQ5OTMsImV4cCI6MjA4MDg1MDk5M30.4IAE_Q-4jhUL9aGb-_TKZ_eSEItS_6F0yRA9CZwSotw"